### ISSUE TITLE
认真学习了，就是有一段代码不是很懂，client/index.html中 ,有一段js,是用来做适配屏幕大小?

### ISSUE THREAD

**Issue by pengrongjie** [gjincai/vue-node-proj#2]

**Comment by flydoing** [comment]
是的，通过这段js来动态改变html的font-size值，配合rem做适配的。详情可参考这里：[移动前端适配](http://gjincai.github.io/2016/09/05/%E7%A7%BB%E5%8A%A8%E5%89%8D%E7%AB%AF%E9%80%82%E9%85%8D%EF%BC%88%E4%BA%8C%EF%BC%89%E5%AE%9E%E8%B7%B5%E7%AF%87/)

**Comment by pengrongjie** [comment]
sidebar,那里写得有点复杂了，login 那里验证码好像没什么用，另外为什么不在vuex中加入登录状态呢

**Comment by flydoing** [comment]
login那里的手机验证码没有做咯；登录状态目前只保存在localStorage里，读出来放在vuex应该会更方便管理登录状态。看得好仔细呀，领教了！
